### PR TITLE
Prepare 3.0.4

### PR DESCRIPTION
**Pull request by jrappen**
* see `CHANGELOG.md` for details

---

**You'll need to tag this yourself, I prepared for `3.0.4`.**

### CODE REVIEW

**Comment by jrappen** [comment]
@dmitrievav ping

**Comment by jrappen** [comment]
@dmitrievav These changes will **NOT** be delivered to users unless you tag the master branch via the <https://github.com/dmitrievav/sublime_gpg/tags> page (as I said above, I prepared for `3.0.4`). As you can see via <https://packagecontrol.io/packages/GPG>, the current release currently still is `3.0.3` on Package Control.

**Comment by jrappen** [comment]
@dmitrievav For consistency's sake, you might want to release that tagged commit from the master branch as well while at it. Compare:

* <https://github.com/dmitrievav/sublime_gpg/tags>
* <https://github.com/dmitrievav/sublime_gpg/releases>

**Comment by dmitrievav** [comment]
done. https://github.com/dmitrievav/sublime_gpg/releases/tag/3.0.4

**Pull request merged**
